### ISSUE TITLE
 VIROU DEV

### ISSUE THREAD

**Issue by vinicioslc** [keyjenn/projeto-curso-git#1]
A partir de agora você não será mais uma simples consumidora de código, mas sim uma produtora.

**Comment by jennysousa** [comment]
Que fique claro que COMECEI PRA VALER HEIN!!

**Comment by vinicioslc** [comment]
Então só irei abrir issues, de cunho construtivo.
AGORA SIM ! JENNYZINHA DEV
Acho que agora já pode fechar a issue não precisamos mais falar deste assunto.
